# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

branches:
  only:
  - master

matrix:
  include:
    ####################
    # platformio build #
    ####################
    - name: platform.io
      language: python
      python:
        - "2.7"

      sudo: false
      cache:
        directories:
          - "~/.platformio"

      install:
        - pip install -U platformio
        - nvm install lts/*
        - npm install -g semantic-release
        - npm install -g semantic-release/exec

      script:
        - platformio run

      deploy:
        provider: script
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        script:
          - npx semantic-release

    ##############################################
    # tests using plain Makefile and google test #
    ##############################################
    - name: unit-tests
      language: c++
      compiler:
        - gcc
      #addons:
      #  apt:
      #    packages:
      #      - lcov

      # install google test
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libgtest-dev cmake
        - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
        - sudo tar xf release-1.8.0.tar.gz
        - cd googletest-release-1.8.0/googletest
        - sudo cmake -DBUILD_SHARED_LIBS=ON .
        - sudo make
        - sudo cp -a include/gtest /usr/include
        - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
        - cd "${TRAVIS_BUILD_DIR}"

      script:
        - make
        - bin/dotest
